inputSet:
  name: Build_Ansiblek8sdeployment_1698395286241-push-trigger-input-set
  identifier: Build_Ansiblek8sdeployment_1698395286241pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: default_project
  pipeline:
    identifier: Build_Ansiblek8sdeployment_1698395286241
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
